<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Microsoft -->
    <PackageVersion Include="CZGL.SystemInfo" Version="2.2.0" />
    <PackageVersion Include="MessagePack" Version="2.5.192" />
    <PackageVersion Include="MessagePackAnalyzer" Version="2.5.192" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    <!-- Third-Party -->
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.2" />
    <PackageVersion Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageVersion Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.7.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.ReDoc" Version="6.7.0" />
    <PackageVersion Include="ConfigureAwait.Fody" Version="3.3.2" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="DistributedLock.Redis" Version="1.0.3" />
    <PackageVersion Include="Fody" Version="6.8.0" />
    <PackageVersion Include="Nigel.Basic" Version="8.2.0" />
    <PackageVersion Include="Polly" Version="8.4.0" />
    <PackageVersion Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.2" />
    <PackageVersion Include="SkiaSharp" Version="2.88.8" />
    <PackageVersion Include="System.Management" Version="10.0.1" />
    <PackageVersion Include="ZXing.Net" Version="0.16.9" />
    <PackageVersion Include="NETCore.Encrypt" Version="2.1.1" />
    <PackageVersion Include="Nigel.Security" Version="6.0.1" />
    <!-- Unit-Test -->
    <!--<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
		<PackageVersion Include="xunit" Version="2.9.0" />
		<PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />-->
  </ItemGroup>
</Project>