<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageProjectUrl>https://github.com/NigelYu/Nigel/tree/master/Source/Nigel.Security</PackageProjectUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>6.2.0-pre1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NETCore.Encrypt" />
    <PackageReference Include="Nigel.Basic" />
  </ItemGroup>

</Project>
